---
- name: Configure SOE
  hosts: myservers
  remote_user: ckoca
  become: yes

  vars:
    - system_owner: cihan.koca@computacenter.com

  tasks:

    - name: Configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
