--- 
- name: Enable internet services 
  hosts: myservers
  become: yes
  tasks: 
    - name: latest version of all required packages installed 
      yum: 
        name: 
          - firewalld 
          - httpd
        state: latest

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: false
        state: stopped

    - name: httpd enabled and running
      service: 
        name: httpd
        enabled: false
        state: stopped

