---
# tasks file for user_perm
- name: Setup Ansible User Permissions
  debug:
    msg:
       - "+--------------------------+"
       - "| Ansible User Permissions |"
       - "+--------------------------+"
 
- name: Check if user exists
  user: 
    name: ckoca
    state: present

- name: Setup Sudoers with nopasswd
  file:
    path: /etc/sudoers.d/ckoca
    state: touch
 
- name: Setup Configuration of Ansible User
  copy:
    content: "ckoca ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/ckoca
  notify: Reload Daemon
